# Generated by Django 5.1.3 on 2025-11-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Counter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(max_length=120)),
                ("src", models.CharField(blank=True, default="", max_length=120)),
                ("count", models.PositiveBigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["event", "src"], name="tracker_cou_event_535437_idx"
                    ),
                    models.Index(fields=["src"], name="tracker_cou_src_367a75_idx"),
                ],
                "unique_together": {("event", "src")},
            },
        ),
    ]
